(define (fast-* a b)
  (*-iter a b 0))
(define (*-iter a count sum)
  (cond ((= count 0) sum)
        ((even? count) (*-iter (double a) (halv count) sum))
        (else (*-iter a (- count 1) (+ sum a)))))
(define (even? n)
  (= (remainder n 2) 0))
(define (double x)
  (+ x x))
(define (halv x)
  (/ x 2))
