(define (integral f a b dx)
  (define (add-dx x) (+ x dx))
  (* (sum f (+ a (/ dx 2.0)) add-dx b)
     dx))
(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a) (sum term (next a) next b))))
(define (simpson f a b n)
  (define h (/ (- b a) n))
  (define (y k) (f (+ a (* k h))))
  (define (simpson-term x)
    (+ (y (- (* 2 x) 2))
       (* 4 (y (- (* 2 x) 1)))
       (y (* 2 x))))
  (define (next i) (+ i 1))
  (* (sum simpson-term 1 next (/ n 2)) (/ h 3)))

(define (cube x)
  (* x x x))
