(define (smooth f)
  (lambda (x)
    (/ (+ (f (- x dx)) (f x) (f (+ x dx))) 3)))
(define dx 0.00001)
;; n重平滑化関数
;; (repeated (smooth f) n)

(define (repeated f n)
  (if (= n 1)
      (lambda (x) (f x))
      (compose f (repeated f (- n 1)))))
(define (compose f g)
  (lambda (x) (f (g x))))
(define (inc n)
  (+ n 1))
(define (square x)
  (* x x))
