(load "../simulator.scm")

(define (make-new-machine)
  (let ((pc (make-register 'pc))
	(flag (make-register 'flag))
	(stack (make-stack))
	(the-instruction-sequence '())
	(number-inst 0)
	(trace-mode #f))
    (let ((the-ops
	    (list
	      (list 'initialize-stack
		    (lambda () (stack 'initialize)))
	      (list 'print-stack-statistics
		    (lambda () (stack 'print-statistics)))))
	  (register-table
	    (list (list 'pc pc) (list 'flag flag))))
      (define (allocate-register name)
	(if (assoc name register-table)
	  (error "Multiply defined register: " name)
	  (set! register-table
	    (cons (list name (make-register name))
		  register-table)))
	'register-allocated)
      (define (lookup-register name)
	(let ((val (assoc name register-table)))
	  (if val
	    (cadr val)
	    (error "Unknown register:" name))))
      (define (execute)
	(let ((insts (get-contents pc)))
	  (if (null? insts)
	    'done
	    (begin
	      (if trace-mode
		(begin
		  (format #t "instruction: ~a" (caar insts))
		  (newline)))
	      ((instruction-execution-proc (car insts)))
	      (set! number-inst (+ 1 number-inst))
	      (execute)))))
      (define (reset-count)
	(set! number-inst 0))
      (define (trace-on)
	(set! trace-mode #t))
      (define (trace-off)
	(set! trace-mode #f))
      (define (dispatch message)
	(cond ((eq? message 'start)
	       (stack 'reset-statistics)
	       (reset-count)
	       (set-contents! pc the-instruction-sequence)
	       (execute))
	  ((eq? message 'install-instruction-sequence)
	   (lambda (seq) (set! the-instruction-sequence seq)))
	  ((eq? message 'allocate-register) allocate-register)
	  ((eq? message 'get-register) lookup-register)
	  ((eq? message 'install-operations)
	   (lambda (ops) (set! the-ops (append the-ops ops))))
	  ((eq? message 'stack) stack)
	  ((eq? message 'operations) the-ops)
	  ((eq? message 'reset-count) (reset-count))
	  ((eq? message 'get-count) number-inst)
	  ((eq? message 'trace-on) (trace-on))
	  ((eq? message 'trace-off) (trace-off))
	  (else (error "Unknown request -- MACHINE" message))))
      dispatch)))

(define (trace-it machine in-value in-register out-register)
  (set-register-contents! machine in-register in-value)
  (machine 'trace-on)
  (start machine)
  (format #t "in:~2d => out:~10d"
	  (get-register-contents machine in-register)
	  (get-register-contents machine out-register))
  (newline))

(define fact-machine
  (make-machine
    '(n continue val)
    (list (list '= =) (list '- -) (list '* *))
    '((assign continue (label fact-done))
      fact-loop
      (test (op =) (reg n) (const 1))
      (branch (label base-case))
      (save continue)
      (save n)
      (assign n (op -) (reg n) (const 1))
      (assign continue (label after-fact))
      (goto (label fact-loop))
      after-fact
      (restore n)
      (restore continue)
      (assign val (op *) (reg n) (reg val))
      (goto (reg continue))
      base-case
      (assign val (const 1))
      (goto (reg continue))
      fact-done)))

(define (fact-to n)
  (define (fact-iter m)
    (if (< m n)
      (begin
	(trace-it fact-machine 'n m 'val)
	(fact-iter (+ m 1)))
      'done))
  (fact-iter 1))

(fact-to 10)
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;in: 1 => out:         1
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 2 => out:         2
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 3 => out:         6
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 4 => out:        24
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 5 => out:       120
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 6 => out:       720
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 7 => out:      5040
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 8 => out:     40320
;instruction: (assign continue (label fact-done))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (save continue)
;instruction: (save n)
;instruction: (assign n (op -) (reg n) (const 1))
;instruction: (assign continue (label after-fact))
;instruction: (goto (label fact-loop))
;instruction: (test (op =) (reg n) (const 1))
;instruction: (branch (label base-case))
;instruction: (assign val (const 1))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;instruction: (restore n)
;instruction: (restore continue)
;instruction: (assign val (op *) (reg n) (reg val))
;instruction: (goto (reg continue))
;in: 9 => out:    362880

