(print-point (midpoint-segment
	      (make-segment (make-point 2 1)
			    (make-point 3 3))))

(define (make-segment p q)
  (cons p q))
(define (start-segment seg)
  (car seg))
(define (end-segment seg)
  (cdr seg))
(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (midpoint-segment seg)
  (make-point (average (x-point (start-segment seg)) (x-point (end-segment seg)))
	      (average (y-point (start-segment seg)) (y-point (end-segment seg)))))
(define (average x y)
  (/ (+ x y) 2))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
