(define (square-list items)
  (if (null? items)
      ()
      (cons (expt (car items) 2) (square-list (cdr items)))))
(define (square-list items)
  (map (lambda (x) (expt x 2)) items))
(square-list (list 1 2 3 4))