(define x (list 1 3 (list 5 7) 9))
(define (x7 li)
  (car (cdr (car (cdr (cdr li))))))
(define y (list (list 7)))
(define (y7 li)
  (car (car li)))
(define z (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7)))))))
(define (z7 li)
  (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr li)))))))))))))
(z7 z)
